[package]
name = "null"
version = "0.1.0"
edition = "2021"

[dependencies]
nasm-to-string={ path="crates/nasm" }
cfg-if = "1.0.0"
once_cell = "1.18.0"
paste = "1.0.14"
phf = { version = "0.11.2", features = ["phf_macros"] }
lazy_static = { version = "1.4.0", features = [] }
